[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_source = """
  let g:NERDTreeShowHidden=1
"""

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']

[[plugins]]
repo = 'cespare/vim-toml'
on-ft = 'toml'

[[plugins]]
repo = 'kana/vim-smartinput'

[[plugins]]
repo = 'simeji/winresizer'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'ajmwagar/vim-deus'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'sheerun/vim-polyglot'
hook_source = """
  let g:polyglot_disabled = ['toml']
"""

