[[plugins]]
repo = 'davidhalter/jedi-vim'

[[plugins]]
repo = 'andviro/flake8-vim'

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'

[[plugins]]
repo = 'bps/vim-textobj-python'

[[plugins]]
repo = 'thinca/vim-quickrun'

